---
sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache: cargo

addons:
  apt:
    packages:
      - libgsl0-dev

git:
  depth: 10

before_install:
  - rustup component add rustfmt

before_script:
  - cargo fmt --all -- --check

# not `after_success` to make sure benchmarks always compile properly
after_script:
  -|
  if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then
      bash .travis/bench_branch_against_master.bash
  fi
