---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  separate-zizmor:
    uses: ./.github/workflows/zizmor.yml
  all-prechecks:
    name: CI precheck success
    needs: [prechecks, separate-zizmor]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
  nix:
    needs: [all-prechecks]
    uses: ./.github/workflows/nix.yml
  unit-tests:
    needs: [all-prechecks]
    uses: ./.github/workflows/test.yml
  docker:
    needs: [nix, unit-tests]
    uses: ./.github/workflows/docker.yml
  all:
    name: CI success
    needs: [unit-tests, docker]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
